
import java.text.DecimalFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gasco1246
 */
public class makingPurchasesGUI extends javax.swing.JFrame {

    /**
     * Creates new form makingPurchasesGUI
     */
    
    public makingPurchasesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        imageLable = new javax.swing.JLabel();
        pizzaPrompt = new javax.swing.JLabel();
        cheeseLable = new javax.swing.JLabel();
        cheeseInput = new javax.swing.JTextField();
        peperoniLable = new javax.swing.JLabel();
        peperoniInput = new javax.swing.JTextField();
        hawaiianLable = new javax.swing.JLabel();
        hawaiianInput = new javax.swing.JTextField();
        drinksPrompt = new javax.swing.JLabel();
        cokeLable = new javax.swing.JLabel();
        cokeInput = new javax.swing.JTextField();
        buyButton = new javax.swing.JButton();
        totalLable = new javax.swing.JLabel();
        subtotalLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(200, 100, 0));

        imageLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PizzaistPizza.png"))); // NOI18N

        pizzaPrompt.setFont(new java.awt.Font("Ti83Pluspc", 0, 14)); // NOI18N
        pizzaPrompt.setText("How many of each type of pizza do you want?");

        cheeseLable.setFont(new java.awt.Font("Ti86pc", 0, 11)); // NOI18N
        cheeseLable.setText("Cheese: $1.79");

        cheeseInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheeseInputActionPerformed(evt);
            }
        });

        peperoniLable.setText("Peperoni:  $1.89");

        peperoniInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peperoniInputActionPerformed(evt);
            }
        });

        hawaiianLable.setText("Hawaiian: $2.09");

        hawaiianInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hawaiianInputActionPerformed(evt);
            }
        });

        drinksPrompt.setText("Do you want any drinks?");

        cokeLable.setText("Coke: $1.49");

        cokeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeInputActionPerformed(evt);
            }
        });

        buyButton.setText("Buy");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        totalLable.setText("Total:");

        subtotalLable.setText("Subtotal:");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(imageLable)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pizzaPrompt)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(buyButton)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                        .addComponent(cokeLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cokeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cheeseLable, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hawaiianLable)
                                            .addComponent(peperoniLable, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cheeseInput, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                            .addComponent(peperoniInput)
                                            .addComponent(hawaiianInput)))))
                            .addComponent(drinksPrompt))
                        .addGap(90, 90, 90)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subtotalLable, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalLable))))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(imageLable, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pizzaPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cheeseLable)
                            .addComponent(cheeseInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtotalLable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(peperoniLable)
                            .addComponent(peperoniInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(totalLable, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hawaiianLable)
                    .addComponent(hawaiianInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(drinksPrompt)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cokeLable)
                    .addComponent(cokeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buyButton)
                .addGap(0, 102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cheeseInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheeseInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cheeseInputActionPerformed

    private void peperoniInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peperoniInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peperoniInputActionPerformed

    private void hawaiianInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hawaiianInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hawaiianInputActionPerformed

    private void cokeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cokeInputActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        
        DecimalFormat form = new DecimalFormat("###.00");
        
        //variable declaration
        int numCheese, numHawaiian, numPeperoni, numCoke;
        final double CHEESE, HAWAIIAN, PEPERONI, COKE, TAX;
        double cheCost, hawCost, pepCost, cokeCost, subtotal, total;
        
        CHEESE = 1.79;
        HAWAIIAN = 2.09;
        PEPERONI = 1.89;
        COKE = 1.49;
        TAX = 1.13;
        
        
        numCheese = Integer.parseInt(cheeseInput.getText());
        numHawaiian = Integer.parseInt(hawaiianInput.getText());
        numPeperoni = Integer.parseInt(peperoniInput.getText());
        numCoke = Integer.parseInt(cokeInput.getText());
        
        
        cheCost = CHEESE*numCheese;
        hawCost = HAWAIIAN*numHawaiian;
        pepCost = PEPERONI*numPeperoni;
        cokeCost = COKE * numCoke;
        
        subtotal = cheCost+hawCost+pepCost+cokeCost;
        
        subtotalLable.setText("Suptotal: $"+form.format(subtotal));
        
        total = subtotal*TAX;
        
        totalLable.setText("Total: $"+form.format(total));
        
                
            
        
        
        
        
    }//GEN-LAST:event_buyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(makingPurchasesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(makingPurchasesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(makingPurchasesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(makingPurchasesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new makingPurchasesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JTextField cheeseInput;
    private javax.swing.JLabel cheeseLable;
    private javax.swing.JTextField cokeInput;
    private javax.swing.JLabel cokeLable;
    private javax.swing.JLabel drinksPrompt;
    private javax.swing.JTextField hawaiianInput;
    private javax.swing.JLabel hawaiianLable;
    private javax.swing.JLabel imageLable;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField peperoniInput;
    private javax.swing.JLabel peperoniLable;
    private javax.swing.JLabel pizzaPrompt;
    private javax.swing.JLabel subtotalLable;
    private javax.swing.JLabel totalLable;
    // End of variables declaration//GEN-END:variables
}
